projects:
  Contentful:
    schemaPath: contentful.graphql
    extensions:
      endpoints:
        production:
          url: 'https://graphql.contentful.com/content/v1/spaces/5u1gaocjmw5v'
          headers:
            Authorization: Bearer 7703763b4b6a3c0267046c7cfa08e6e051a195fc1ad29fb31aaa2a67e88e2a54
        development: 'http://localhost:4000'
